version: '3.8'

services:
  vnc-simple:
    image: consol/ubuntu-xfce-vnc:latest
    ports:
      - "5901:5901"
    environment:
      - VNC_PW=123456
    container_name: vnc_simple_test
    restart: unless-stopped