[supervisord]
nodaemon=true

[program:vnc]
command=/usr/bin/Xvnc :1 -geometry 1280x800 -depth 24 -rfbport 5901 -rfbauth /home/vncuser/.vnc/passwd -alwaysshared -dontdisconnect -desktop "Ubuntu VNC"
user=vncuser
autostart=true
autorestart=true
environment=HOME="/home/vncuser",USER="vncuser"

[program:xfce]
command=/usr/bin/startxfce4
user=vncuser
autostart=true
autorestart=true
environment=DISPLAY=":1",HOME="/home/vncuser",USER="vncuser"