version: '3'
services:
  ftp:
    image: bogem/ftp
    container_name: ftp-test
    environment:
      - FTP_USER=admin
      - FTP_PASS=123456
      - PASV_ADDRESS=127.0.0.1
      - PASV_MIN_PORT=30000
      - PASV_MAX_PORT=30100
    ports:
      - "21:21"
      - "20:20"
      - "30000-30100:30000-30100"
    restart: unless-stopped