version: '3.8'

services:
  activemq:
    build: .
    ports:
      - "61613:61613"  # STOMP
      - "61616:61616"  # OpenWire
      - "8162:8161"    # Web Console (mapped to host port 8162)
    environment:
      - ACTIVEMQ_ADMIN_LOGIN=admin
      - ACTIVEMQ_ADMIN_PASSWORD=Aa123456789
    volumes:
      - ./activemq.xml:/opt/activemq/conf/activemq.xml
      - ./users.properties:/opt/activemq/conf/users.properties